# -*- coding: utf-8 -*-
"""yoloV5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cdaVsXb0uQy_xq_pBZHUxOpX-e5Xa7rJ

# **SUBSCRIBE to the [channel](https://www.youtube.com/user/19daredevill?sub_confirmation=1) to learn cool things**

**Step 1 : Clone yolov5 repository**
"""

!git clone https://github.com/ultralytics/yolov5.git

"""**Step 2: Change Directory to yolov5**"""

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5/

"""**Step 3: Install Dependencies**"""

!pip install -U -r requirements.txt

"""**Step 4: Run Object Detection on Images. Provide image path. Upload image in the inference/images/ folder**"""

!python detect.py --source ./inference/images/zidane.jpg --weights yolov5s.pt --conf 0.4

"""**Step 5: Display image in colab**"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import matplotlib.pyplot as plt
# %matplotlib inline

image = cv2.imread("inference/output/zidane.jpg")
height, width = image.shape[:2]
resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)

fig = plt.gcf()
fig.set_size_inches(18, 10)
plt.axis("off")
plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
plt.show()

"""**Object Detection on Videos. Create a folder under inference/ called "videos", under which you can upload the video file and then provide the file path below**"""

!python detect.py --source inference/videos/running.mp4 --weights yolov5s.pt --conf 0.4